language: python
python:
- 3.5
- 3.6
- 3.6-dev
- 3.7-dev
- nightly

# Scripts to install dependencies
install:
- pip install -e .[test]

# Run tests
script:
- pre-commit run --all-files
- nosetests -svv
